name: Build on PRs

on:
  pull_request:
    branches: [ main, develop ]

env:
  ECR_REPOSITORY: naturescot/standard-forestry-operations
  SFO_PORT: 3002
  SFO_SESSION_SECRET: override_this_value
  SFO_API_URL: override_this_value

jobs:

  build:
    name: Build the Image
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install all the pre-requisites
      run: npm ci && npm prune --production

    - name: Check the pre-start operations
      run: npm run prestart

    - name: Build the Docker Image
      run: docker build --tag $ECR_REPOSITORY:${GITHUB_SHA} .
